<a href="https://colab.research.google.com/github/manhanton/test_15June/blob/main/Data_prep_DDE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import numpy as np
import datetime as dt
import os
import datetime as dt

In [6]:
# #please don't use `list` as a variable name.
# file_list = ['.csv']

# def yield_dfs(file_list):
#     """generator function to yield dataframes."""
#     for file_name in file_list:
#         df = pd.read_csv(file_name)
#         # you may be able to reduce the memory requirements by doing some pre-processing of the dataframe here. e.g. convert strings to booleans so save memore.
#         yield df

# df = pd.concat(yield_dfs(file_list))

In [25]:
import pandas as pd
path = "/content/drive/MyDrive/rawdata.csv"
df = pd.read_csv(path)
df.head()

,Run Name,Run Start Time,Tool Group,Tool ID,Tool Description,Tool Area,Chamber ID,Chamber Description,Chamber Number,Sensor Kind,...,TDS: Trigger: CEID15328; CE_15328_StripRemovedClamp2,TDS: Trigger: CEID15329; CE_15329_StripLeftClamp2,TDS: Trigger: CEID15330; CE_15330_StripArrivedClamp3,TDS: Trigger: CEID15331; CE_15331_StripInsertedClamp3,TDS: Trigger: CEID15338; CE_15338_StripRemovedClamp3,TDS: Trigger: CEID15339; CE_15339_StripLeftClamp3,TDS: Trigger: CEID15651; CE_15651_DispenseProcessDone,TDS: Trigger: CEID15652; CE_15652_BondProcessDone,TDS: Trigger: CEID15653; CE_15653_PickProcessDone,TDS: Trigger: CEID3211; CE_3211_EnterExecProcessState
0,\\TW7K20190008\c\Inficon\data\Chamber 2\2020-0...,3/19/2020 1:02,ESEC 2100sD Die Bonder,ES-177,ESEC 2100sD Die Bonder ES1201,C5 1F,Chamber 2,Glue Dispensing,2,TDS,...,23094.497,501.559,501.559,61328.763,61328.763,296.714,9994.017,9983.362,1421.871,11275.612
1,\\TW7K20190008\c\Inficon\data\Chamber 2\2020-0...,3/19/2020 1:02,ESEC 2100sD Die Bonder,ES-177,ESEC 2100sD Die Bonder ES1201,C5 1F,Chamber 2,Glue Dispensing,2,TDS,...,23094.606,501.668,501.668,61328.872,61328.872,296.823,9994.126,9983.471,1421.980,11275.721
2,\\TW7K20190008\c\Inficon\data\Chamber 2\2020-0...,3/19/2020 1:02,ESEC 2100sD Die Bonder,ES-177,ESEC 2100sD Die Bonder ES1201,C5 1F,Chamber 2,Glue Dispensing,2,TDS,...,23094.716,501.778,501.778,61328.982,61328.982,296.933,9994.236,9983.581,1422.090,11275.831
3,\\TW7K20190008\c\Inficon\data\Chamber 2\2020-0...,3/19/2020 1:02,ESEC 2100sD Die Bonder,ES-177,ESEC 2100sD Die Bonder ES1201,C5 1F,Chamber 2,Glue Dispensing,2,TDS,...,23094.825,501.887,501.887,61329.091,61329.091,297.042,9994.345,9983.690,1422.199,11275.940
4,\\TW7K20190008\c\Inficon\data\Chamber 2\2020-0...,3/19/2020 1:02,ESEC 2100sD Die Bonder,ES-177,ESEC 2100sD Die Bonder ES1201,C5 1F,Chamber 2,Glue Dispensing,2,TDS,...,23094.934,501.996,501.996,61329.200,61329.200,297.151,9994.454,9983.799,1422.308,11276.049

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115927 entries, 0 to 115926
Data columns (total 59 columns):
 #   Column                                                             Non-Null Count   Dtype
---  ------                                                             --------------   -----
 0   Run Name                                                           115927 non-null  object
 1   Run Start Time                                                     115927 non-null  object
 2   Tool Group                                                         115927 non-null  object
 3   Tool ID                                                            115927 non-null  object
 4   Tool Description                                                   115927 non-null  object
 5   Tool Area                                                          115927 non-null  object
 6   Chamber ID                                                         115927 non-null  object
 7   Chamber Description                                                115927 non-null  object
 8   Chamber Number                                                     115927 non-null  int64
 9   Sensor Kind                                                        115927 non-null  object
 10  Lot ID                                                             115927 non-null  object
 11  Cassette ID                                                        115927 non-null  object
 12  Slot ID                                                            115927 non-null  object
 13  Substrate ID                                                       115927 non-null  object
 14  Part ID                                                            115927 non-null  object
 15  Layer ID                                                           115927 non-null  object
 16  Technology ID                                                      115927 non-null  object
 17  Operator ID                                                        115927 non-null  object
 18  Sequence ID                                                        115927 non-null  object
 19  Recipe ID                                                          115927 non-null  object
 20  Blade Z1 ID                                                        115927 non-null  object
 21  Blade Z2 ID                                                        115927 non-null  object
 22  Port ID                                                            115927 non-null  object
 23  Chuck ID                                                           115927 non-null  object
 24  FullProductDescription ID                                          115927 non-null  object
 25  Dispense Strip ID                                                  115927 non-null  object
 26  Bond Strip ID                                                      115927 non-null  object
 27  Extra 6 ID                                                         115927 non-null  object
 28  Extra 7 ID                                                         115927 non-null  object
 29  Extra 8 ID                                                         115927 non-null  object
 30  Step Number                                                        115927 non-null  int64
 31  Time                                                               115927 non-null  object
 32  TDS: Latch: LA_251920465_DispenseHeightToStrip_ECRO; CEID15651.10  115927 non-null  float64
 33  TDS: Latch: LA_251920580_DispenserPressure_ECRO; CEID15651.9       115927 non-null  int64
 34  TDS: Latch: LA_269353054_DevicePositionXOnLFAtP1; CEID15651.4      115927 non-null  int64
 35  TDS: Latch: LA_269353055_DevicePositionYOnLFAtP1; CEID15651.5      115927 non-null  int64
 36  TDS: Latch: LA_269353092_DispenseCurrentBondPosition; CEID15651.6  115927 non-null  int64
 37  TDS: Latch: LA_269353094_DispenseProcessAvePress; CEID15651.7      115927 non-null  int64
 38  TDS: Latch: LA_269353095_DispenseProcessAveZHeight; CEID15651.8    115927 non-null  float64
 39  TDS: Sig: DispenseProcess_AvePress (post Step)                     115927 non-null  float64
 40  TDS: Sig: DispenseProcess_AveZHeight (post Step)                   115927 non-null  float64
 41  TDS: Sig: Framing - Dispense Process Done (post Step)              115927 non-null  float64
 42  TDS: Status                                                        115927 non-null  int64
 43  TDS: Tool Bin Data Age                                             115927 non-null  int64
 44  TDS: Tool Bin Polling Latency                                      115927 non-null  int64
 45  TDS: Trigger: CEID15310; CE_15310_StripArrivedClamp1               115927 non-null  float64
 46  TDS: Trigger: CEID15318; CE_15318_StripRemovedClamp1               115927 non-null  float64
 47  TDS: Trigger: CEID15319; CE_15319_StripLeftClamp1                  115927 non-null  float64
 48  TDS: Trigger: CEID15320; CE_15320_StripArrivedClamp2               115927 non-null  float64
 49  TDS: Trigger: CEID15328; CE_15328_StripRemovedClamp2               115927 non-null  float64
 50  TDS: Trigger: CEID15329; CE_15329_StripLeftClamp2                  115927 non-null  float64
 51  TDS: Trigger: CEID15330; CE_15330_StripArrivedClamp3               115927 non-null  float64
 52  TDS: Trigger: CEID15331; CE_15331_StripInsertedClamp3              115927 non-null  float64
 53  TDS: Trigger: CEID15338; CE_15338_StripRemovedClamp3               115927 non-null  float64
 54  TDS: Trigger: CEID15339; CE_15339_StripLeftClamp3                  115927 non-null  float64
 55  TDS: Trigger: CEID15651; CE_15651_DispenseProcessDone              115927 non-null  float64
 56  TDS: Trigger: CEID15652; CE_15652_BondProcessDone                  115927 non-null  float64
 57  TDS: Trigger: CEID15653; CE_15653_PickProcessDone                  115927 non-null  float64
 58  TDS: Trigger: CEID3211; CE_3211_EnterExecProcessState              115927 non-null  float64
dtypes: float64(19), int64(10), object(30)
memory usage: 52.2+ MB

In [27]:
df['Run Start Time'] = pd.to_datetime(df['Run Start Time'])

In [28]:
df['Run Start Time']

0        2020-03-19 01:02:00
1        2020-03-19 01:02:00
2        2020-03-19 01:02:00
3        2020-03-19 01:02:00
4        2020-03-19 01:02:00
                 ...
115922   2020-03-19 05:59:00
115923   2020-03-19 05:59:00
115924   2020-03-19 05:59:00
115925   2020-03-19 05:59:00
115926   2020-03-19 05:59:00
Name: Run Start Time, Length: 115927, dtype: datetime64[ns]

In [29]:
df['Date_Run_Start_Time'] = df['Run Start Time'].dt.date

In [30]:
df['Date_Run_Start_Time']

0         2020-03-19
1         2020-03-19
2         2020-03-19
3         2020-03-19
4         2020-03-19
             ...
115922    2020-03-19
115923    2020-03-19
115924    2020-03-19
115925    2020-03-19
115926    2020-03-19
Name: Date_Run_Start_Time, Length: 115927, dtype: object

In [31]:
df['Time_Run_Start'] = df['Run Start Time'].dt.time

In [35]:
type(df['Time_Run_Start'])

pandas.core.series.Series

In [34]:
df[["Time_Run_Start","Date_Run_Start_Time","Run Start Time"]].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115927 entries, 0 to 115926
Data columns (total 3 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Time_Run_Start       115927 non-null  object
 1   Date_Run_Start_Time  115927 non-null  object
 2   Run Start Time       115927 non-null  datetime64[ns]
dtypes: datetime64[ns](1), object(2)
memory usage: 2.7+ MB

In [39]:
df["Time"]

0         02:57.0
1         02:57.1
2         02:57.2
3         02:57.3
4         02:57.5
           ...
115922    00:03.9
115923    00:04.0
115924    00:03.1
115925    00:03.2
115926    00:03.3
Name: Time, Length: 115927, dtype: object

In [40]:
df[["Time_Run_Start","Date_Run_Start_Time","Run Start Time","Time"]]

       Time_Run_Start Date_Run_Start_Time      Run Start Time     Time
0            01:02:00          2020-03-19 2020-03-19 01:02:00  02:57.0
1            01:02:00          2020-03-19 2020-03-19 01:02:00  02:57.1
2            01:02:00          2020-03-19 2020-03-19 01:02:00  02:57.2
3            01:02:00          2020-03-19 2020-03-19 01:02:00  02:57.3
4            01:02:00          2020-03-19 2020-03-19 01:02:00  02:57.5
...               ...                 ...                 ...      ...
115922       05:59:00          2020-03-19 2020-03-19 05:59:00  00:03.9
115923       05:59:00          2020-03-19 2020-03-19 05:59:00  00:04.0
115924       05:59:00          2020-03-19 2020-03-19 05:59:00  00:03.1
115925       05:59:00          2020-03-19 2020-03-19 05:59:00  00:03.2
115926       05:59:00          2020-03-19 2020-03-19 05:59:00  00:03.3

[115927 rows x 4 columns]

# Selected the TDS

In [40]:
"""

Try to understand the data content from files that Russell provided to me for Die Bond use cases

Talk to local engineer guys, who in the Die bond process

And now I got some ideas to talk tomorrow with Carl and team about what I have been through. Have you ever found some data issue about insufficient data?
Like time frequent domain, how can we extract smth from that based on our current data.


"""

In [43]:
df[["Run Start Time","Time","TDS: Latch: LA_251920465_DispenseHeightToStrip_ECRO; CEID15651.10","TDS: Latch: LA_251920580_DispenserPressure_ECRO; CEID15651.9"]]

,Run Start Time,Time,TDS: Latch: LA_251920465_DispenseHeightToStrip_ECRO; CEID15651.10,TDS: Latch: LA_251920580_DispenserPressure_ECRO; CEID15651.9
0,2020-03-19 01:02:00,02:57.0,0.00012,170000
1,2020-03-19 01:02:00,02:57.1,0.00012,170000
2,2020-03-19 01:02:00,02:57.2,0.00012,170000
3,2020-03-19 01:02:00,02:57.3,0.00012,170000
4,2020-03-19 01:02:00,02:57.5,0.00012,170000
...,...,...,...,...
115922,2020-03-19 05:59:00,00:03.9,0.00012,70000
115923,2020-03-19 05:59:00,00:04.0,0.00012,70000
115924,2020-03-19 05:59:00,00:03.1,0.00012,70000
115925,2020-03-19 05:59:00,00:03.2,0.00012,70000
115926,2020-03-19 05:59:00,00:03.3,0.00012,70000